version: '3'

services:
  user-database:
    image: postgres:14.12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Runs on port 5432 docker
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z

  user-cache:
    image: redis:7.2.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    # Runs on 6379 Docker
    volumes:
      - ./redisdata:/data:z

  user-api:
    build: .
    # Sleep to wait for redis/postgreSQL to initalize...
    command: >
      bash -c "
        sleep ${STARTUP_DELAY} &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - ./src:/code:z
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - user-database
      - user-cache