version: '3'

services:
  user-database:
    image: postgres:14.12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z

  user-cache:
    image: redis:7.2.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ./redisdata:/data:z

  user-api:
    build: .
    # Sleep to wait for redis/postgreSQL to initalize...
    command: >
      bash -c "
        sleep ${STARTUP_DELAY} &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - ./src:/code:z
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - user-database
      - user-cache

  pgadmin:
    image: dpage/pgadmin4:8.6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"  # Mapping internal port 80 to custom external port
    depends_on:
      - user-database