# Generated by Django 4.2.8 on 2024-05-10 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
                ('encrypted_email', models.CharField(max_length=128, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.CharField(max_length=128, unique=True)),
                ('encrypted_client_info', models.CharField(max_length=128)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 6, 9, 12, 9, 27, 728954, tzinfo=datetime.timezone.utc))),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='OTPSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_totp_code', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='OTPBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_backup_code', models.TextField()),
                ('otp_secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.otpsecret')),
            ],
        ),
    ]
