# Generated by Django 4.2.8 on 2024-05-13 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('hashed_password', models.CharField(max_length=64)),
                ('encrypted_email', models.CharField(max_length=512)),
                ('hashed_email', models.CharField(max_length=64, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('VERBOSE', 'Verbose'), ('DEBUG', 'Debug'), ('LOG', 'Log'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='LOG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFASecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_twofa_code', models.CharField(max_length=512)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.account')),
            ],
        ),
        migrations.CreateModel(
            name='TwoFABackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_backup_code', models.CharField(max_length=64)),
                ('otp_secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.twofasecret')),
            ],
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(max_length=64, unique=True)),
                ('encrypted_client_info', models.CharField(max_length=1024)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 6, 12, 14, 0, 47, 804825, tzinfo=datetime.timezone.utc))),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.account')),
            ],
        ),
    ]
