# Generated by Django 4.2.8 on 2024-05-13 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hashed_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 14, 11, 16, 632855, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='twofabackup',
            name='hashed_backup_code',
            field=models.CharField(max_length=128),
        ),
    ]
