# Generated by Django 4.2.8 on 2024-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_account_hashed_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
