# Generated by Django 4.2.8 on 2024-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_alter_sessiontoken_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('LOCKED', 'Locked'), ('BANNED', 'Banned')], default='OK', max_length=10),
        ),
    ]
