# Generated by Django 4.2.8 on 2024-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_alter_sessiontoken_encrypted_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='hashed_token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
