# Generated by Django 4.2.8 on 2024-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0007_alter_sessiontoken_hashed_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPasswords',
            fields=[
                ('password', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
