# Generated by Django 4.2.8 on 2024-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_commonpasswords'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauthenticationtoken',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailauthenticationtoken',
            name='purpose',
            field=models.CharField(choices=[('VERIFY', 'VERIFY'), ('PASSWORD_RESET', 'PASSWORD_RESET')], default='VERIFY', max_length=20),
        ),
    ]
