# Generated by Django 4.2.8 on 2024-07-01 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_emailauthenticationtoken_consumed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.account')),
            ],
        ),
    ]
