# Generated by Django 4.2.8 on 2024-07-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0011_remove_twofasecret_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAuthenticationToken',
        ),
    ]
