# Generated by Django 4.2.8 on 2024-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0012_delete_emailauthenticationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
